name:                parse4s
version:             0.1.0.0
author:              TZ
maintainer:          tz@academ.email
copyright:           "2018"
category:            parsing
extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs:      src
  dependencies:
  - base >= 4.7 && < 5
  - lucid
  - text
  - optparse-applicative
  - megaparsec
  - parser-combinators
  ghc-options:
  - -Wall
  - -Werror
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wmissing-fields
  - -fwrite-ide-info
  - -hiedir=.hie

executables:
  parse4s-exe:
    source-dirs:      app
    main:             Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -Wmissing-fields
    - -fwrite-ide-info
    - -hiedir=.hie
    dependencies:
      - parse4s

tests:
  parse4s-test:
    source-dirs:      test
    main:             Main.hs
    dependencies:
    - parse4s
    - QuickCheck
    - hedgehog
    - hspec
    - megaparsec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -Wmissing-fields
    - -fwrite-ide-info
    - -hiedir=.hie





