flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:
- HUnit-1.6.0.0
- QuickCheck-2.10.0.1
- ansi-terminal-0.6.3.1
- ansi-wl-pprint-0.6.8
- async-2.1.1.1
- base-compat-0.9.3
- call-stack-0.1.0
- cpphs-1.20.8
- derive-2.6.3
- exceptions-0.8.3
- hashable-1.2.6.1
- haskell-src-exts-1.19.1
- hspec-2.4.4
- hspec-core-2.4.4
- hspec-discover-2.4.4
- hspec-expectations-0.8.2
- integer-logarithms-1.0.2
- megaparsec-5.3.1
- mtl-2.2.1
- old-locale-1.0.0.7
- old-time-1.1.0.3
- optparse-applicative-0.14.0.0
- polyparse-1.12
- primitive-0.6.2.0
- quickcheck-io-0.2.0
- random-1.1
- scientific-0.3.5.2
- setenv-0.1.1.3
- stm-2.4.4.1
- syb-0.7
- text-1.2.2.2
- tf-random-0.5
- transformers-compat-0.5.1.4
- uniplate-1.6.12
- unordered-containers-0.2.8.0
resolver: ghc-8.2.1
