flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:
- HUnit-1.6.0.0
- QuickCheck-2.10.0.1
- ansi-terminal-0.6.3.1
- ansi-wl-pprint-0.6.8
- async-2.1.1.1
- call-stack-0.1.0
- hspec-2.4.4
- hspec-core-2.4.4
- hspec-discover-2.4.4
- hspec-expectations-0.8.2
- mtl-2.2.1
- optparse-applicative-0.14.0.0
- parsec-3.1.11
- primitive-0.6.2.0
- quickcheck-io-0.2.0
- random-1.1
- setenv-0.1.1.3
- stm-2.4.4.1
- text-1.2.2.2
- tf-random-0.5
- transformers-compat-0.5.1.4
- ghc-paths-0.1.0.9
- syb-0.7

resolver: ghc-8.2.1
